### ISSUE TITLE
No multi-language support?

### ISSUE THREAD

**Issue by Crolug** [getgrav/grav-plugin-sitemap#42]
Did I do something wrong or the plugin doesn't recognize additional languages?

**Comment by flaviocopes** [comment]
@Crolug can you provide more info on how to replicate your problem? Works for me

**Comment by ktaranov** [comment]
Hi, @flaviocopes . Same problem, example: http://sqlserver-kit.org/sitemap
Latest version of plugin: 1.9.1

**Comment by jimblue** [comment]
Same problem here, multi-language is not supported.

http://wplang.org/sitemaps-multiple-languages-wordpress/

**Comment by Crolug** [comment]
Yes, thank you @jimblue , this article sums it up nicely how the multi-language sitemap should look like. That's what I meant - this plugin doesn't work that way afaik.

**Comment by rhukster** [comment]
No one interested in trying to create a pull request to implement the multi-language sitemap format?

**Comment by jimblue** [comment]
Sorry @rhukster I have no idea how to do that 😞 I'm not really a dev

**Comment by jimblue** [comment]
@rhukster trying to understand the code, maybe it just miss something like `for each language` before this?

https://github.com/getgrav/grav-plugin-sitemap/blob/756479720d19148834f3a59cbbae67e828180d6b/sitemap.php#L68

**Comment by jimblue** [comment]
Any idea?

**Comment by rhukster** [comment]
This does require some thinking and a better solution.  I've not got time to look into it now, but if someone can help, that would be appreciated.

**Comment by jimblue** [comment]
Hi @rhukster and thanks for answering. Sorry to heard the problem is more complicated than I tough. Still I'll try to understand it better but I'm not sure I can really help. Hope someone more competent than me will be able to help 😄. Cheers

**Comment by humhann** [comment]
There luckily already is multilanguage support (since April 2017, version 1.9.1)!

What crawlers see is `sitemap.xml`:
<img width="986" alt="sitemap-xml" src="https://user-images.githubusercontent.com/5189297/35487754-75a3970a-047f-11e8-9e0e-a9ba320ce11f.png">
Note how for each page, their counterparts in other languages are provided.

What we see when opening `/sitemap` in browser is styled by `sitemap.xsl`, where some parameters are hidden:
<img width="986" alt="sitemap-xsl" src="https://user-images.githubusercontent.com/5189297/35487791-c8e91124-047f-11e8-8e66-65284c9b8dd3.png">

So all information needed for efficient multilanguage sitemap is already there for Google and other crawlers to see, but is hidden when viewing styles in browser.

**Comment by humhann** [comment]
If styling in `sitemap.xsl` should be changed so that it is more apparent that multilanguage support is implemented is another question. It might make sense to avoid confusions like these?

**Comment by fabbow** [comment]
I agree that the styling should be changed or removed rather. What's missing in the implementation of the hreflang though is an x-default and the route of the URL instead of the raw route if someone uses a translated alias for the URL. I just started using Grav and am absolutely not sure how to do this, but I'll try digging into this.

**Comment by fabbow** [comment]
Okay, so apparently there's no clean way of doing this (or I have yet to find it).
What I do now is to CURL through the raw route URLs and use the redirects final destination for the sitemap. This is obviously very bad, but I prefer a clean sitemap to clean code... Could anyone give me a hint on how to cache the sitemap properly?

**Comment by 01Kuzma** [comment]
No any updates?

**Comment by rhukster** [comment]
The current PR #83 is pretty beefy and needs to be thoroughly tested before we will able to merge and release a new version. I suggest checking out this PR and testing it for yourself and letting us know how it works.

**Comment by 01Kuzma** [comment]
I've downloaded two files from PR #83 and replaced originals and the result is negative.
Now a URL `http://localhost/project/LANG_CODE/sitemap`
loads and shows some data (before it there was no any links), but rendered links are without the language code inside. They are pointing to the same default's language data.

**Comment by rhukster** [comment]
Multilang support has been rewritten and significantly improved.  Please try v3.0
