### ISSUE TITLE
Add support for x-default for multilingual sites

### ISSUE THREAD

**Issue by ptarmic** [getgrav/grav-plugin-sitemap#90]
Can x-default be supported for multilingual sites?

It needs one extra "default" line added to each page to show which language to default to if the user's language isn't available. For example US and UK english would default to the "en" link but also Chinese would default to the "en" link since there's no Chinese page.

example:
```xml
<url>
<loc>https://example.com/blog/blog-article</loc> 
<xhtml:link rel="alternate" hreflang="x-default" href="https://example.com/blog/blog-article" />
<xhtml:link rel="alternate" hreflang="en" href="https://example.com/blog/blog-article" /> 
<xhtml:link rel="alternate" hreflang="de" href="https://example.com/blog/de/blog-article" /> 
<xhtml:link rel="alternate" hreflang="zh" href="https://example.com/blog/zh/blog-article" /> 
</url>
```

**Comment by rhukster** [comment]
I was thinking about this when I implemented the multi-lang additions the other day.  The thing is that Grav is internally handling the fallback to English if there is no translation.  ie. you may not have translated the `zh` page, but if you have fallback enabled, it will show the English version when you access the `/zh` URL.

Right now, with fallback enabled, you get all the languages displayed even if they don't have a unique translation.  This also handles the case where you might be using the `[language]` shortcode on a single English page to handle small chunks of translation where needed.

So as of right now, there's no need for `x-default` because you will always have a link for each language even if there's not a unique translated page. Also linking back to English with an `x-default` will switch you to the English version of the site, which is not ideal, that's why the fallbacks working internally to 'display' the English version when you request `/zh` but it's not translated work better.

**Comment by pierrejoye** [comment]
One thing about multiple languages and all translated pages in sitemap is the non usage of the slug but the route only. If a slug is defined, it could be used instead as it can be a translated version of the default route. What do you think?

**Comment by rhukster** [comment]
right now it's using the canonical route which will include a custom slug for a specific language.

**Comment by pierrejoye** [comment]
In master right?

I am using master, and for example:

Page EN:

---
title: 'Reducing Loss'
---


The VN page adds:
title: 'Giảm thất thoát'
slug: 'Giảm thất thoát'

and so does the Thai one (with Thai translation for the slug). The resulting sitemap entry is as follow:

sitemap:
  <url>
    <loc>http://localhost:8080/en/news%20&amp;%20blog/reducing-loss</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://localhost:8080/en/news%20&%20blog/reducing-loss" />
    <xhtml:link rel="alternate" hreflang="th" href="http://localhost:8080/th/news%20&%20blog/reducing-loss" />
    <lastmod>2021-01-27</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
VI does not show and TH is not using the slug. The folder is also translated by the way.

Should I expect the slug to be used, or what is shown here is the expected behaviors?

If there is a bug or this behavior is not the one desired, I can dig in and provide a PR, please let me know :)

**Comment by pierrejoye** [comment]
Btw, thank a lot for adding alternative syntax already! :)

**Comment by rhukster** [comment]
The multilang improvements are in develop not master.

**Comment by pierrejoye** [comment]
Sorry, I am using 'develop' yes.

**Comment by rhukster** [comment]
Ok, ok you've convinced me.. i'll take a look at your PR tomorrow

**Comment by rhukster** [comment]
hreflang x-default support has been added to develop
